name: flutter_incall_manager
description: Flutter InCall Manager plugin for iOS.
version: 0.1.0
homepage: https://github.com/kangshaojun/flutter-incall-manager

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterIncallManagerPlugin

environment:
  sdk: '>=2.18.4 <3.0.0'
